### ISSUE TITLE
won't work in android when compileSdkVersion is 25

### ISSUE THREAD

**Issue by ngrj** [tanguyantoine/react-native-music-control#91]
# My react native project requires minimum comileSdkversion to be 25, when I update the build.gradle file accordingly the package does not work and it raised error when I try setNowPlaying

1. Sample code (provide repo url or sample code)
I changed the build.gradle file like this:
`android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
}
`

2. Platform ?
   - [ ] Android
   

   
3. Device
  - [ ] Simulator
  - [ ] Real device

4. Error  
`java.lang.NullPointerException: name is null
at android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:214)
at android.content.res.Resources.getIdentifier(Resources.java:1873)
at com.tanguyantoine.react.MusicControlNotification.setCustomNotificationIcon(MusicControlNotification.java:46)
at com.tanguyantoine.react.MusicControlModule.setNowPlaying(MusicControlModule.java:210)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:154)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
at java.lang.Thread.run(Thread.java:761)
`

The values I'm setting is valid, since the code works well in ios, also thanks for this awesome plugin.
If you can guide me I can try to fix this.
I've asked same question on [SO](https://stackoverflow.com/questions/46214447/ive-two-different-react-native-packages-which-require-different-android-compile) with no response
Ps: sorry if there was something wrong with my Issue structure

**Comment by jdemangeon** [comment]
:+1:

**Comment by Guichaguri** [comment]
It was a crash introduced by @mzmiric5's PR. Fixed in https://github.com/tanguyantoine/react-native-music-control/commit/761813acf0d7290b8bf7bca8f885115a41736485

**Comment by tanguyantoine** [comment]
Version bump ?

**Comment by Guichaguri** [comment]
Done.

**Comment by tanguyantoine** [comment]
faster than flash

**Comment by jdemangeon** [comment]
Thanks =) It's maybe the right moment to introduce unit tests to avoid regressions ?

**Comment by ngrj** [comment]
Hi really thanks for the awesome work,
I've updated the package now I'm receiving this error:

`Exception in native call
E/unknown:React(16859): java.lang.RuntimeException: Could not invoke MusicControlManager.setNowPlaying
E/unknown:React(16859):     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:382)
E/unknown:React(16859):     at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
E/unknown:React(16859):     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React(16859):     at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:React(16859):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React(16859):     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React(16859):     at android.os.Looper.loop(Looper.java:136)
E/unknown:React(16859):     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
E/unknown:React(16859):     at java.lang.Thread.run(Thread.java:841)
E/unknown:React(16859): Caused by: java.lang.reflect.InvocationTargetException
E/unknown:React(16859):     at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:React(16859):     at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:React(16859):     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
E/unknown:React(16859):     ... 8 more
E/unknown:React(16859): Caused by: java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
E/unknown:React(16859):     at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
E/unknown:React(16859):     at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
E/unknown:React(16859):     at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1729)
E/unknown:React(16859):     at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1649)
E/unknown:React(16859):     at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:408)
E/unknown:React(16859):     at com.tanguyantoine.react.MusicControlModule.setNowPlaying(MusicControlModule.java:250)
E/unknown:React(16859):     ... 11 more
W/unknown:React(16859): Invoking JS callback after bridge has been destroyed.
`

This is the same error I was receiving before I updated the package from 0.4.4

Edit: My Phone Android version is 4.4.4, it works well in 6.0.0

**Comment by tanguyantoine** [comment]
@jdemangeon your pr is welcome ;-)

**Comment by Guichaguri** [comment]
@ngrj This looks like an issue with the support library, not with this module. Can you refresh the dependencies and try again, please?

**Comment by ngrj** [comment]
okay will do that, thanks
